### PR TITLE
created BenefitCustomCreateProperties with default note to None

### PR DESCRIPTION
**Pull request by nareshNishad**
Fix issue #4005 
Create a BenefitCustomCreateProperties same as others CreateProperties in schema

### CODE REVIEW

**Comment by frankie567** [comment]
Thank you @nareshNishad, but that's not the way it works in our codebase ☺️

The schema is auto-generated from actual Python (Pydantic) models. So the changes should rather happen over here: https://github.com/polarsource/polar/blob/07dfb2b56a1473ec3ad041e7c1893a08bcc30e5b/server/polar/benefit/schemas.py#L60

**Comment by nareshNishad** [comment]
Thanks @frankie567 for guiding, i will make the changes.

**Comment by nareshNishad** [comment]
@frankie567 updated the code, let me know anything else I can update in it.

**Review by frankie567 — CHANGES_REQUESTED** [review]
That's exactly it, thank you @nareshNishad 🙏 

If you can just revert the changes on `sdk/schema.json` (it's auto-updated by a CI workflow), we should be good to go then.

**Comment by nareshNishad** [comment]
@frankie567  Removed schema.json changes.

**Comment by frankie567** [comment]
Took the liberty to fix a small typing issue. Thank you for your help in fixing this @nareshNishad :pray:

**Comment by nareshNishad** [comment]
Sorry for being negligent about the test case, I will make sure about these in future contributions.

**Pull request merged**
