### PR TITLE
Implement new design of issue page's left part

### PR DESCRIPTION
**Pull request by frankie567**
I've implemented the first bits of the new issue presentation on the Pledge page.

Related to #1201 and #1200 

## Screenshots

Capture d’écran 2023-09-21 à 15 04 03

Capture d’écran 2023-09-21 à 15 04 10

## What we have ✅

* General presentation of the issue (title, number, author, number of comments and reactions)
* Current pledge and optional goal
* Rendered issue description ✨
* Repository details with number of stars
* Optional upfront rewards split notice

## What we miss compared to the design 😞

* Pledgers avatars
    * Component is ready, but still unsure about the API to retrieve them (cf our discussions related to #1210)
* List of rewarded people
    * Feature is not yet implemented AFAIK?
* List of linked PR 
    * We should implement an API to retrieve this data for an issue

## Next steps

What I propose is to merge and deploy those changes, even if we have some holes compared to the design, and address them in follow-up improvements.

The page looks already quite good and it can be a good first-step. What do you think @birkjernstrom?

### CODE REVIEW

**Comment by birkjernstrom** [comment]
Awesome! Going to be really awesome to have this additional data, updated design and now with all the added functionality as well. Overall, I love it and great work! Below are some specific and smaller feedback to make it shippable and :chef-kiss:

1. Can we use our markdown component for the title to ensure backticks are styled and that the backticks themselves don't show? E.g `example`
2. Same for the issue body. They seem to be styled with bold at least (which is sufficient), but can we get rid of the backticks?
3. Why is the block that we show in dark mode in the light theme? Can we only get one mode and that it's then cached I assume? If so, let's cache one for each mode to ensure it's light in the light theme.
4. Margin between issue title and the author is too little. I have 10px in Figma, but that might be to little too. But let's get some space in-between there
5. Funding amount & goal progress bar are too big. I know they are in the design too, but it became more apparent now. Can we try reducing them by 50%. At least the progress bar to 3px in height. Potentially that the funding amount only needs to be reduced down to 18px

Can you also share a screenshot of what this looks like on mobile? I think we might potentially need to get rid of the issue body on mobile to avoid too much scrolling. Potentially just the title, author, funding and then the funding section.

**Comment by frankie567** [comment]
Thanks for the detailed feedback, @birkjernstrom 🙏  I'll tackle those points!

Regarding **2** and **3**, this is actually because of [Tailwind Typography plugin](https://tailwindcss.com/docs/typography-plugin). Its purpose is to put default styling for content you don't own (which is exactly our case here). So, that's why you have bold titles, and code blocks on dark background. Those can be tweaked — to a certain extent. I'll try to work on your specific points.

Regarding mobile, I tried to work on responsiveness so it should look okay, but yeah, the issue body might take lot of spaces. Here it is (iPhone XR mode):

<details>
  <summary>Open screenshot</summary>
  
</details>

**Comment by birkjernstrom** [comment]
This is great and glad we did the small tweaks - looks better.

Just some small things left on mobile and then this is ready to ship.

1. Hide issue body
2. Hide rewards. I think mobile can be more focused on funding vs. contribution and rewards with the added context. At least for now. Want to save as much space as possible so that the funding module is above the fold to make things clear right off the bat. 
3. Let's left align the org details on mobile. We can hide the number of stars as well I think.

Finally, I noticed there is a lot of whitespace on mobile in the payment form. I assume this might be a timing issue of when the screenshot was taken and that it's Stripe being loaded there so that there isn't any whitespace in reality?

**Comment by frankie567** [comment]
Done!

<details>
    <summary>Mobile light mode</summary>
    
</details>

<details>
    <summary>Mobile dark mode</summary>
    
</details>

> Finally, I noticed there is a lot of whitespace on mobile in the payment form. I assume this might be a timing issue of when the screenshot was taken and that it's Stripe being loaded there so that there isn't any whitespace in reality?

Yes, probably, it corresponds to size of the CC form. Doesn't happen in the screenshot I took today

**Comment by birkjernstrom** [comment]
Great! Two final things that I noticed now. Actually outside the scope of this PR, but part of the funding form. Would be great if you could fix them while you're at it:
1. Add margin to the funding amount summary after the country dropdown. They are glued together now, but we should have the same spacing between them as everything else.
2. "Save credit card on file". Moving the checkbox up next to the label. I think we can remove the label underneath. For our audience I don't think it adds much and only takes up space. Same here re: margin to the pledge button underneath too. 

Those are the final things I can see. Then we can ship this which is going to be awesome! :)

**Pull request merged**
