### PR TITLE
Add support for importing subscribers from mailchimp

### PR DESCRIPTION
**Pull request by patrick91**
Mailchimp uses "Email Address" as the column name:

image

Let me know if you want me to add a test :)

### CODE REVIEW

**Comment by emilwidlund** [comment]
🥳

**Comment by birkjernstrom** [comment]
@patrick91 You're just amazing - thank you. No tests required on this one. Merging shortly.

**Comment by emilwidlund** [comment]
@patrick91 This fix is now deployed.

**Comment by patrick91** [comment]
@emilwidlund @birkjernstrom thanks!

CleanShot 2024-01-08 at 11 08 32@2x

**Pull request merged**
