### PR TITLE
server/checkout: implement a new Checkout API to replace SubscribeSession

### PR DESCRIPTION
**Pull request by frankie567**

### CODE REVIEW

**Comment by birkjernstrom** [comment]
Ping me before we deploy this one. I know of a user who uses this in production and would want to give them the heads-up and ability to migrate quickly once we deploy it 🙂

**Comment by frankie567** [comment]
@birkjernstrom This is ready.

**Before**

```
POST /subscriptions/subscribe-sessions/

{
    "tier_id": "SUBSCRIPTION_TIER_ID",
    "price_id": "PRICE_ID",
    "success_url": "https://example.com",
}
```

**After**

```
POST /checkouts/

{
    "product_price_id": "PRICE_ID",
    "success_url": "https://example.com",
}
```

**Comment by birkjernstrom** [comment]
Awesome! Thanks @frankie567 - I've reached out to the affected user(s) and hope to have the all-clear shortly to proceed with merging.

**Comment by birkjernstrom** [comment]
We can deploy at your will @frankie567. Ping me on Discord once you're done and I can confirm it with them 🙂

**Pull request merged**
